# access.yml file has been copied from
# https://github.com/dev-sec/ansible-windows-hardening
---
- name: Verify the Windows folder permissions are properly set
  win_file:
    path: C:\windows
    state: directory
  tags:
    - Level-1

- name: Safe DLL Search Mode is Enabled
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Session Manager
    name: "SafeDllSearchMode"
    data: "1"
    type: dword
  tags:
    - Level-1
    - section-18
    - "18.4.8"
    - scored

- name: Anonymous Access to Windows Shares and Named Pipes is Disallowed
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters
    name: "RestrictNullSessAccess"
    data: "1"
    type: dword
  tags:
    - Level-1
    - section-2
    - "2.3.10.10"
    - scored

- name: All Shares are Configured to Prevent Anonymous Access
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters
    name: "NullSessionShares"
    data: []
    type: multistring
  tags:
    - Level-1
    - section-2
    - "2.3.10.12"
    - scored

- name: Force Encrypted Windows Network Passwords
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters
    name: "EnablePlainTextPassword"
    data: "0"
    type: dword
  tags:
    - Level-1
    - section-2
    - "2.3.8.3"
    - scored

## Duplicate setting to that found in AdminisitrativeTemplates.yml
#- name: Disable SMB1 to Windows Shares
#  win_regedit:
#    path: HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters
#    name: "SMB1"
#    data: "0"
#    type: dword
#  tags:
#    - Level-1
#    - section-18
#    - "18.3.3"
#    - scored

## Conflict. Set to 5 already in HealthWindowsSecurityRemediation.yml which satisfies CIS as well as win2016ewrc_rule_70
## data:4 is incorrect. It sets "Send NTLMv2 response only. Refuse LM"
#- name: Strong Windows NTLMv2 Authentication Enabled; Weak LM Disabled
#  win_regedit:
#    path: HKLM:\System\CurrentControlSet\Control\Lsa
#    name: "LmCompatibilityLevel"
#    data: "4"
#    type: dword
#  tags:
#    - Level-1
#    - section-2
#    - "2.3.11.7"
#    - scored

- name: Enable Strong Encryption for Windows Network Sessions on Clients
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    name: NtlmMinClientSec
    type: dword
    data: 537395200
  tags:
    - Level-1
    - section-2
    - "2.3.11.9"
    - scored

- name: Enable Strong Encryption for Windows Network Sessions on Servers
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    name: NtlmMinServerSec
    type: dword
    data: 537395200
  tags:
    - Level-1
    - section-2
    - "2.3.11.10"
    - scored

- name: Ensure Accounts Block Microsoft accounts is set to Users can't add or log on with Microsoft accounts
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: NoConnectedUser
    type: dword
    data: 3
  tags:
    - Level-1
    - section-2
    - "2.3.1.2"
    - scored

- name: Ensure 'Do not display last user name' is set to enabled
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: DontDisplayLastUserName
    type: dword
    data: 1
  tags:
    - Level-1
    - section-2
    - "2.3.7.1"
    - scored

- name: Ensure 'Interactive logon Machine inactivity limit' is set to '900 or fewer second(s), but not 0'
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: InactivityTimeoutSecs
    type: dword
    data: 900
  tags:
    - Level-1
    - section-2
    - "2.3.7.3"
    - scored

- name: Configure 'Interactive logon Message text for users attempting to log on'
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: LegalNoticeText
    data: >
      1. Acceptable use means work activities which support learning,
      communication and information gathering in a responsible, ethical and
      legal manner.

      2. Staff are expected to use the communications technology facilities for
      purposes of their work during their work hours.  Such use includes
      communications with individuals and organisations external to NSW Health.
      The Ministrys Code of Conduct applies to the use of communication systems
      and devices. Reasonable and responsible personal use of the Internet and
      e-mail is permissible but such use is not currently considered as having
      the same personal privacy rights as using private facilities.

      3. Unacceptable use of the facility which may lead to removal of
      privileges or disciplinary action.

      4. Access to the facility is via user passwords.  The user is responsible
      at all times for the proper use of the password and for all access under
      the password, which should be complex and changed regularly to prevent
      misuse. It is a violation of conditions of use to use another's password
      or allow yours to be used

      5. Computer records are maintained for all usage of passwords to access
      sites. Access to any user may be limited or denied at the Director
      General's discretion.

      6. The Department monitors its computer resources to protect the
      integrity of its computing systems, workstations and programs and
      maintains records of access including, messages, inquiries and sites
      visited by you when using the computer system.

  tags:
    - Level-1
    - section-2
    - "2.3.7.4"
    - scored

- name: Configure 'Interactive logon Message title for users attempting to log on'
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: LegalNoticeCaption
    data: "Conditions Of Access"
  tags:
    - Level-1
    - section-2
    - "2.3.7.5"
    - scored

- name: Ensure 'Interactive logon Require Domain Controller Authentication to unlock workstation' is set to 'Enabled'
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: ForceUnlockLogon
    type: dword
    data: 1
  tags:
    - Level-1
    - section-2
    - "2.3.7.8"
    - scored

- name: Ensure 'Interactive logon Smart card removal behavior' is set to 'Lock Workstation' or higher
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: ScRemoveOption
    data: 1
  tags:
    - Level-1
    - section-2
    - "2.3.7.9"
    - scored

- name: Ensure 'Microsoft network client Digitally sign communications (always)' is set to 'Enabled'
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
    name: RequireSecuritySignature
    type: dword
    data: 1
  tags:
    - Level-1
    - section-2
    - "2.3.8.1"
    - scored

- name: Ensure 'Microsoft network server Digitally sign communications (always)' is set to 'Enabled'
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
    name: RequireSecuritySignature
    type: dword
    data: 1
  tags:
    - Level-1
    - section-2
    - "2.3.9.2"
    - scored

- name: Ensure 'Microsoft network server Digitally sign communications (if client agrees)' is set to 'Enabled'
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
    name: EnableSecuritySignature
    type: dword
    data: 1
  tags:
    - Level-1
    - section-2
    - "2.3.9.2"
    - scored

- name: Ensure 'Microsoft network server Server SPN target name validation level' is set to 'Accept if provided by client' or higher
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
    name: SMBServerNameHardeningLevel
    type: dword
    data: 1
  tags:
    - Level-1
    - section-2
    - "2.3.9.5"
    - scored

- name: Ensure 'Network access Do not allow anonymous enumeration of SAM accounts and shares' is set to 'Enabled'
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: RestrictAnonymous
    type: dword
    data: 1
  tags:
    - Level-1
    - section-2
    - "2.3.10.3"
    - scored

- name: Ensure 'Network access Do not allow storage of passwords and credentials for network authentication' is set to 'Enabled'
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: RestrictAnonymous
    type: dword
    data: 1
  tags:
    - Level-1
    - section-2
    - "2.3.10.4"
    - scored

- name: Ensure 'Network security Allow Local System to use computer identity for NTLM' is set to 'Enabled'
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: UseMachineId
    type: dword
    data: 1
  tags:
    - Level-1
    - section-2
    - "2.3.11.1"
    - scored
