---
- name: No auto-restart with logged on users for scheduled automatic updates installations
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: "NoAutoRebootWithLoggedOnUsers"
    data: "0"
    type: dword
  tags:
    - level-1
    - section-18
    - "18.9.101.4"
    - scored

- name: Configure Automatic Updates - disabled
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: "ScheduledInstallDay"
    data: "1"
    type: dword
  tags:
    - level-1
    - section-18
    - "18.9.101.3"
    - scored

- name: No auto-restart with logged on users for scheduled automatic updates installations
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: "NoAutoUpdate"
    data: "0"
    type: dword
  tags:
    - level-1
    - section-18
    - "18.9.101.2"
    - scored
