---
- name: Ensure Screen Saver is Active
  win_regedit:
    path: 'HKCU:\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop'
    name: "ScreenSaveActive"
    data: 1
    type: dword
  tags:
    - level-1
    - section-19
    - "19.1.3.1"
    - scored

- name: Force specific screen saver scrnsave.scr
  win_regedit:
    path: 'HKCU:\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop'
    name: "SCRNSAVE.EXE"
    data: 'scrnsave.scr'
    type: string
  tags:
    - level-1
    - section-19
    - "19.1.3.2"
    - scored

- name: Password protect the screen saver
  win_regedit:
    path: 'HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop'
    name: "ScreenSaverIsSecure"
    data: 1
    type: dword
  tags:
    - level-1
    - section-19
    - "19.1.3.3"
    - scored

- name: Screen saver timeout set to 900 i.e 15 minutes
  win_regedit:
    path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
    name: "ScreenSaveTimeOut"
    data: "900"
    type: dword
  tags:
    - level-1
    - section-19
    - "19.1.3.4"
    - scored

- name: Turn off toast notifications on the lock screen
  win_regedit:
    path: HKCU:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications
    name: NoToastApplicationNotificationOnLockScreen
    type: dword
    data: 1
  tags:
    - level-1
    - section-19
    - "19.5.1.1"
    - scored

- name: Do not preserve zone information in file attachments
  win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments
    name: "SaveZoneInformation"
    data: "2"
    type: dword
  tags:
    - level-1
    - section-19
    - "19.7.4.1"
    - scored

- name: Notify antivirus programs when opening attachments
  win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments
    name: "ScanWithAntiVirus"
    data: "3"
    type: dword
  tags:
    - level-1
    - section-19
    - "19.7.4.2"
    - scored

- name: Ensure 'Configure Windows spotlight on lock screen' is set to Disabled'
  win_regedit:
    path: HKCU:\Software\Policies\Microsoft\Windows\CloudContent
    name: "ConfigureWindowsSpotlight"
    data: "2"
    type: dword
  tags:
    - level-1
    - section-19
    - "19.7.7.1"
    - scored

- name: Do not suggest third-party content in Windows spotlight
  win_regedit:
    path: HKCU:\Software\Policies\Microsoft\Windows\CloudContent
    name: "DisableThirdPartySuggestions"
    data: "1"
    type: dword
  tags:
    - level-1
    - section-19
    - "19.7.7.2"
    - scored

- name: Always install with elevated privileges is set to Disabled
  win_regedit:
    path: HKCU:\Software\Policies\Microsoft\Windows\Installer
    name: "AlwaysInstallElevated"
    data: "0"
    type: dword
  tags:
    - level-1
    - section-19
    - "19.7.40.1"
    - scored
