---
- name:
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Parameters
    name: "LDAPServerIntegrity"
    data: "0"
    type: dword
  tags:
    - level-1
    - section-2
    - "2.3.5.2"
    - scored

- name:
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
    name: "RequireSignOrSeal"
    data: "1"
    type: dword
  tags:
    - level-1
    - section-2
    - "2.3.6.2"
    - scored

- name: Disabled Interactive logon required for domain controllers
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: "ForceUnlockLogon"
    data: "0"
    type: dword
  tags:
    - level-1
    - section-2
    - "2.3.7.8"
    - scored

- name: Disable autologoff after hours
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
    name: "enableforcedlogoff"
    data: "0"
    type: dword
  tags:
    - level-1
    - section-2
    - "2.3.9.4"
    - scored

- name: Disabled Windows INK workspace
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace
    name: "AllowWindowsInkWorkspace"
    data: "0"
    type: dword
  tags:
    - level-1
    - section-18
    - "18.9.84.2"
    - scored
