---
- name: Microsoft Online Accounts | microsoft-online-accounts
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\PolicyManager\default\Settings\AllowYourAccount
    name: "value"
    data: "0"
    type: dword

- name: Disable Windows Store | disable-windows-store
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore
    name: "AutoDownload"
    data: "4"
    type: dword