---
- name: Set Enforce password history to 24 or more passwords | cis enforce-password-history 1.1.1
  win_security_policy:
    section: System Access
    key: PasswordHistorySize
    value: 24
  tags:
    - level-1
    - section-1
    - "1.1.1"
    - scored

- name: Set Maximum password age to 90 days
  win_security_policy:
    section: System Access
    key: MaximumPasswordAge
    value: 60
  tags:
    - level-1
    - section-1
    - "1.1.2"
    - scored

- name: Set Minimum password age to 1 day
  win_security_policy:
    section: System Access
    key: MinimumPasswordAge
    value: 1
  tags:
    - level-1
    - section-1
    - "1.1.3"
    - scored

- name: Set Minimum password length to 8
  win_security_policy:
    section: System Access
    key: MinimumPasswordLength
    value: 14
  tags:
    - level-1
    - section-1
    - "1.1.4"
    - scored

- name: Do not store passwords using reversible encryption
  win_security_policy:
    section: System Access
    key: ClearTextPassword
    value: 0
  tags:
    - level-1
    - section-1
    - "1.1.6"
    - scored

- name: Password must meet complexity requirements
  win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 1
  tags:
    - level-1
    - section-1
    - "1.1.5"
    - scored

- name: Account lockout threshold
  win_security_policy:
    section: System Access
    key: LockoutBadCount
    value: 10
  tags:
    - level-1
    - section-1
    - "1.2.2"
    - scored

- name: Reset account lockout counter after 15 minutes
  win_security_policy:
    section: System Access
    key: ResetLockoutCount
    value: 15
  tags:
    - level-1
    - section-1
    - "1.2.3"
    - scored

- name: Account lockout duration
  win_security_policy:
    section: System Access
    key: LockoutDuration
    value: 900
  tags:
    - level-1
    - section-1
    - "1.2.1"
    - scored
